InformedSolutions/JAQU-CAZ-Payments-UI

Gemfile, Gemfile.lock, app/controllers/local_authorities_controller.rb, app/views/local_authorities/index.html.haml, config/environments/test.rb, features/local_authorities.feature, features/refunds.feature, features/step_definitions/helper_steps.rb, features/step_definitions/local_authorities_steps.rb, features/step_definitions/non_uk_vehicles_steps.rb, features/step_definitions/path_expectations.rb, features/step_definitions/vehicle_steps.rb, features/step_definitions/welcome_steps.rb, features/support/env.rb, features/support/session_helper.rb, features/vehicles.feature
https://eaflood.atlassian.net/browse/CAZ-1153
I used `request.referer` to determine the previous path.
Also, I refactored feature tests and added gem for hijacking session in cucumber test.
Go to the choosing LA page by 3 ways:
- Choose the UK as registration country, confirm details
- Choose the UK as registration country, do NOT confirm details, continue on incorrect details page
- Choose non UK as registration country, select some type of vehicle
=> [CAZ-1153] Add back button to LAs page

app/views/non_uk_vehicles/choose_type.html.haml, app/views/welcome/index.html.haml
Fix error position for choose type page.
Also remove opening a new tab for refund link.
=> [NT] Fix error position for choose type page

app/views/non_uk_vehicles/choose_type.html.haml, config/brakeman.ignore
We don't need the Taxi/PHV option for non UK vehicles in the form.
https://eaflood.atlassian.net/browse/CAZ-1283
Removed option from select. 
I tried to load the form for the non UK car.
=> [CAZ-1283] Removed Taxi/PHV option from non_uk vehicle form

app/javascript/styles/application.scss, app/views/charges/daily_charge.html.haml, app/views/charges/dates.html.haml, app/views/charges/local_authority.html.haml, app/views/charges/review_payment.html.haml, app/views/common/_draft_tag.html.haml, app/views/govuk_pay/index.html.haml, app/views/non_uk_vehicles/choose_type.html.haml, app/views/non_uk_vehicles/index.html.haml, app/views/refunds/details.html.haml, app/views/refunds/scenarios.html.haml, app/views/vehicles/compliant.html.haml, app/views/vehicles/details.html.haml, app/views/vehicles/enter_details.html.haml, app/views/vehicles/incorrect_details.html.haml, app/views/vehicles/unrecognised.html.haml, app/views/welcome/index.html.haml
https://eaflood.atlassian.net/browse/CAZ-1284
We need to add a Draft Content tag on every page in the Payments app. 
Added partial with new tag 
Used partial on every page. 
Tried to view all pages in payment app.
=> [CAZ-1284] Add draft tag to every page

config/initializers/session_store.rb
Changing SameSite session cookie policy to allow the session to be loaded after redirect from GOV.UK Pay
Policy changed from `:strict` to `:lax`
=> [NT] Change same site policy

app/controllers/payments_controller.rb, features/payments.feature, features/step_definitions/payments_steps.rb, spec/requests/payments_controller/failure_spec.rb, spec/requests/payments_controller/success_spec.rb
https://eaflood.atlassian.net/browse/CAZ-1343
Vehicle details were cleared too harsh. Now only those related to the payment are getting deleted after payment finalization.
Go through the payment process and on success payment page click link described in the card.
=> [CAZ-1343] Fix link on successful payment page

app/views/payments/failure.html.haml, features/payments.feature
https://eaflood.atlassian.net/browse/CAZ-1338
Just added a link with a feature test.
=> [CAZ-1338] Add restart link to the failure page

app/controllers/vehicles_controller.rb, app/models/vehicle_details.rb, spec/models/vehicle_details_spec.rb, spec/requests/vehicles_controller/details_spec.rb, spec/requests/vehicles_controller/submit_details_spec.rb
[Link to JIRA card](https://eaflood.atlassian.net/browse/CAZ-1333)
* Updated `VehicleDetails` model to include `exempt` field
* In `submit_details` action I added check which verifies if vehicle is exempted and redirects when needed.
* Added specs
* Manually
* With RSpec
Video is in the comment on JIRA card
=> [CAZ-1333] Redirect to compliant page when vehicle is exempted

app/controllers/charges_controller.rb, app/helpers/application_helper.rb, app/helpers/dates_helper.rb, app/views/charges/local_authority.html.haml, app/views/dates/select_daily_date.html.haml, app/views/dates/select_weekly_date.html.haml, features/step_definitions/charges_steps.rb, features/support/session_helper.rb, spec/helpers/application_helper_spec.rb, spec/helpers/dates_helper_spec.rb, spec/rails_helper.rb, spec/requests/charges_controller/review_payment_spec.rb, spec/support/shared_examples/without_charge_in_session.rb, spec/support/shared_examples/without_la_name_in_session.rb, spec/support/test_session_monkey_patch.rb
I noticed that the back button on the review page does not lead to the previous page but to some earlier step. 
Also, checkboxes on picking dates should be marked when you go back.
=> [NT] Fix review back button and checking inputs on date select

app/api_wrapper/compliance_checker_api.rb, app/controllers/vehicles_controller.rb, app/models/vehicle_details.rb, app/services/session_manipulation/base_manipulator.rb, app/services/session_manipulation/set_compliance_details.rb, app/services/session_manipulation/set_leeds_taxi.rb, spec/fixtures/files/vehicle_details_taxi_response.json, spec/models/vehicle_details_spec.rb, spec/requests/charges_controller/submit_local_authority_spec.rb, spec/requests/vehicles_controller/details_spec.rb, spec/services/session_manipulation/clear_payment_details_spec.rb, spec/services/session_manipulation/set_compliance_details_spec.rb, spec/services/session_manipulation/set_leeds_taxi_spec.rb
https://eaflood.atlassian.net/browse/CAZ-1370
added `.leeds_taxi?` to `VehcileDetails` which determines whether to add `leeds_taxi: true` to the session or not/.
=> [CAZ-1370] Change Leeds taxi recognition

app/api_wrapper/compliance_checker_api.rb, app/models/compliance_details.rb, app/services/chargeable_zones_service.rb, spec/fixtures/files/caz_list_response.json, spec/fixtures/files/unrecognised_one_charge_response.json, spec/fixtures/files/unrecognised_vehicle_response.json, spec/fixtures/files/vehicle_compliance_many_charges_response.json, spec/fixtures/files/vehicle_compliance_one_charge_response.json, spec/models/compliance_details_spec.rb, spec/services/chargeable_zones_service_spec.rb, spec/support/api_mocks.rb, spec/support/shared_examples/chareable_zones_service.rb
https://eaflood.atlassian.net/browse/CAZ-1497
`ChareableZoneService` know will iterate over compliance data the same way for DVLA and non-DVLA vehicles
=> [CAZ-1497] Fix fetching chargeable LAs for non-DVLA

app/services/vehicle_types.rb, spec/services/vehicle_types_spec.rb
The Tariff Service no longer has a concept of 'Small Van' and 'Large Van' - necessitating a merge of the two into 'Van'.
Specification for Vehicle Type service has been updated to only expect 7 types of vehicles for unrecognised and non-UK vehicles.
=> Merge small and large van types into one

app/views/vehicles/enter_details.html.haml
https://eaflood.atlassian.net/browse/CAZ-1906
=> [Fix] [CAZ-1906] Reverse errors on enter_details.html.haml

app/models/compliance_details.rb, spec/models/compliance_details_spec.rb
https://eaflood.atlassian.net/browse/CAZ-1910
The type was not saved for UK vehicles and it is not present in the compliance response. 
However, we can find the type in the `tariff_code` eg. `BCC01-CAR`
=> [CAZ-1910] [Fix] Fix dynamic links

app/models/vrn_form.rb, spec/models/vrn_form_spec.rb
https://eaflood.atlassian.net/browse/CAZ-1918
Add format check for non_UK VRNs
=> [FIX] [CAZ-1918] Add non-UK VRN format check

app/views/payments/failure.html.haml, app/views/payments/success.html.haml
Updates references to Charge reference such that they read Payment ID following discussion with Product Owner
=> Remove charge reference terms in favour of Payment ID

app/api_wrapper/compliance_checker_api.rb
**THIS PR IS WIP AND CANNOT BE MERGED UNTIL ALL PROXY ENDPOINTS ARE IN PLACE**
API Calls were made from Payments UI to VCCS API which is against
architecture we are building. Now with proxy endpoints being added
on top of Payments API we can now move all API calls there.
https://eaflood.atlassian.net/browse/CAZ-2047
This commit makes sure we are not making any direct API calls to VCCS API layer,
but instead are using newly created proxy endpoints under Payments API Gateway.
It is needed to be consistent with C4 models, and respect system boundaries.
To my knowledge this is configuration change that is going to be tested on DEV environment
DO NOT APPLY
=> [CAZ-2047] Proxy VCCS calls through Payments API

app/api_wrapper/compliance_checker_api.rb, app/controllers/non_dvla_vehicles_controller.rb, app/models/whitelisted_vehicle.rb, features/step_definitions/vehicle_steps.rb, features/support/mock_helper.rb, features/vehicles.feature, spec/api_wrappers/compliance_checker_api/whitelisted_vehicle_spec.rb, spec/fixtures/files/whitelisted_vehicle_response.json, spec/models/whitelisted_vehicle_spec.rb, spec/requests/non_dvla_vehicles_controller/index_spec.rb
https://eaflood.atlassian.net/browse/CAZB-1160
* When provided `non-uk` vehicle, the redirection behaves in a similar way as when provided `UK` vrn. 
Manually, unit tests, integration specs in progress.
=> [CAZB-1160] Api call for non-uk exemption

app/controllers/charges_controller.rb, app/controllers/vehicles_controller.rb, app/models/compliance_details.rb, app/models/vehicle_details.rb, app/services/chargeable_zones_service.rb, app/services/session_manipulation/base_manipulator.rb, app/services/session_manipulation/set_undetermined.rb, app/views/vehicles/enter_details.html.haml, features/step_definitions/vehicle_steps.rb, features/support/mock_helper.rb, features/vehicles.feature, spec/fixtures/files/undetermined_vehicle_details_response.json, spec/models/vehicle_details_spec.rb, spec/services/session_manipulation/set_undetermined_spec.rb
https://eaflood.atlassian.net/browse/CAZ-2111
Fix Payment process for a vehicle without type where compliance returns 200 status
Added the edge case when the details do not contain TYPE but compliance returns 200 instead of 422. 
Tested with many vrns (for example PAY017, TST009, TST010, TST011, CAS309)
=> [CAZ-2111] Fix Payment for Undetermined vehicle.

app/services/chargeable_zones_service.rb, features/step_definitions/vehicle_steps.rb, features/support/mock_helper.rb, features/vehicles.feature, spec/api_wrappers/compliance_checker_api/clean_air_zones_spec.rb, spec/fixtures/files/unchargeable_caz_list_response.json, spec/services/chargeable_zones_service_spec.rb, spec/support/api_mocks.rb
https://eaflood.atlassian.net/browse/CAZ-2708
* Updated `ChargeableZonesService` to consider also the `active_charge_start_date` parameter when selecting the chargeable CAZes
* Updated specs
* Set `active_charge_start_date` on sample cleanAirZone to be in the future.
* Click through the flow:
* Payments UI main page
* `Start Now >`
* Insert VRN which is not whitelisted/exempted
* Select UK or non-UK - doesn't matter
* Confirm vehicle details
* On the `Which Clean Air Zone do you need to pay for?` page, the sample cleanAirZone should not be visible.
* When all CAZes are chargeable:
* When one CAZ is chargeable:
* When no CAZes are chargeable:
=> [CAZ-2708] Removed non-chargeable CAZes from CAZ selection page

app/javascript/styles/datepicker.scss, app/views/dates/select_weekly_date_input/_normal.html.haml
https://eaflood.atlassian.net/browse/CAZ-2847
Disable calendar icon when javascript is disabled on Leeds Taxi weekly selection
Manually, by checking after js being disabled
=> [CAZ-2847] Disable calendar in Leeds weekly selection when JS is disabled

app/controllers/payments_controller.rb, app/services/session_manipulation/base_manipulator.rb, app/services/session_manipulation/calculate_total_charge.rb, app/services/session_manipulation/set_charge_period.rb, app/services/session_manipulation/set_chargeable_zones.rb, app/services/session_manipulation/set_compliance_details.rb, app/services/session_manipulation/set_confirm_exempt.rb, app/services/session_manipulation/set_confirm_registration.rb, app/services/session_manipulation/set_confirm_vehicle.rb, app/services/session_manipulation/set_confirm_weekly_charge_today.rb, app/services/session_manipulation/set_incorrect.rb, app/services/session_manipulation/set_leeds_taxi.rb, app/services/session_manipulation/set_payment_details.rb, app/services/session_manipulation/set_payment_id.rb, app/services/session_manipulation/set_type.rb, app/services/session_manipulation/set_undetermined.rb, app/services/session_manipulation/set_unrecognised.rb, app/services/session_manipulation/set_weekly_charge_today.rb, app/views/vehicles/country_input/_normal.html.haml, spec/requests/payments_controller/create_spec.rb, spec/services/session_manipulation/clear_session_details_spec.rb
https://eaflood.atlassian.net/browse/CAZ-2860?focusedCommentId=220422 Fix for AC3
Remember country selection in session
Manually, test updated
=> [CAZ-2860] Fix remember Non-Uk selection for fraud process

app/javascript/packs/datePicker.js, app/javascript/src/compatibilityHelpers.js
https://eaflood.atlassian.net/browse/CAZ-2846
Safari (as well as IE11) is unable to parse date in `YYYY-MM-DD` format without preceding zeros, eg. `2020-6-1`. This caused all days to be clickable. Added checking if the browser is Safari and adding zeros if needed
Expected behavior: only available days are highlighted
Incorrect behavior: all days are available
=> [CAZ-2846] Fix datepicker on Safari

app/models/vrn_form.rb, spec/models/vrn_form_spec.rb
JIRA Card: https://eaflood.atlassian.net/browse/CAZB-1944
* When provided VRN begins with `0` and is marked as the UK, the validation is going to fail due to the wrong format.
* There are possible 2-characters formats like `9A`. Considering the card requirements it should be possible now to pass a single character VRNs for cases like `0G` but after consultation, it was decided that minimal length of VRN should remain 2.
* Updated specs.
* Manually.
=> [CAZB-1944] Expect VRNs without leading zeros in the VRN form

.env.example, app/helpers/application_helper.rb, app/views/vehicles/uk_registered_details.html.haml
https://eaflood.atlassian.net/browse/CAZB-2194
Use url to DVLA contact form from env variable
Manually
=> [CAZB-2194] Use DVLA_CONTACT_URL on "Your vehicle is UK registered" page

app/controllers/charges_controller.rb, features/charges.feature, features/step_definitions/non_uk_vehicles_steps.rb, features/support/session_helper.rb
https://eaflood.atlassian.net/browse/CAZB-2200
* Added `if` statement for scenario when vehicle is vehicle is UK based but not found in the DVLA - back button then follows back to the vehicle type selection page.
Manually and cucumber.
N/A
=> [CAZB-2200] Back button flow for unrecognised vehicle

app/controllers/dates_controller.rb
Adding this statement setting `second_week_selected` on the first date selection page prevents a scenario where you:
1. Select a start date
2. Go to the review page
3. Click back
4. Click continue once again
5. Are shown an error where you have selected dates previously selected
I think the new back link work means for some reason this isn't getting set elsewhere and thus not triggering validation, but I'm not sure why. Possibly something to investigate further next sprint.
=> [NON-JIRA] set second week to false on first week page

additional_url.yml, app/models/compliance_details.rb, spec/models/compliance_details_spec.rb, spec/requests/dates_controller/daily_charges_spec.rb, spec/requests/dates_controller/weekly_charges_spec.rb, spec/requests/payments_controller/success_spec.rb
Jira card: https://eaflood.atlassian.net/browse/CAZB-2826
When url is not found in `additonal_url.yml` we should use `become_compliant_url`
Added rspec
=> [CAZB-2826] Use become_compliant_url as dynamic_compliance_url

app/views/layouts/_footer.html.haml, app/views/static_pages/privacy_notice.html.haml, features/static_pages.feature
https://eaflood.atlassian.net/browse/CAZB-2978
Change Privacy notice in footer and in text occurence
Manually, existing test fixed
=> [CAZB-2978] IOD - typo on Privacy notice

app/controllers/vehicles_controller.rb, app/views/vehicles/country_input/_common.html.haml, app/views/vehicles/vrn_input/_normal.html.haml, features/payments.feature, features/step_definitions/charges_steps.rb
https://eaflood.atlassian.net/browse/CAZB-2893
After clicking `Pay for another vehicle`:
Instead of clearing the VRN from the session, it's preserved in the session and not displayed in the input. Thanks to this, after clicking `Pay for another CAZ` VRN doesn't have to be entered again.
=> [CAZB-2893] Fix back button navigation after successful payment

app/controllers/vehicles_controller.rb, app/views/vehicles/country_input/_common.html.haml, app/views/vehicles/vrn_input/_normal.html.haml, features/payments.feature, features/step_definitions/charges_steps.rb
https://eaflood.atlassian.net/browse/CAZB-2577
The case featured in bug report video (https://eaflood.atlassian.net/browse/CAZB-2578?focusedCommentId=229926) was already fixed, but after clicking Continue button with empty form, old values reappeared. Added variable to hide session values on rerender and use only values from `params`
Manually, cucumber
=> [CAZB-2577] Improve input handling for Pay for another vehicle link

app/controllers/payments_controller.rb, spec/requests/payments_controller/success_spec.rb
https://eaflood.atlassian.net/browse/CAZB-2893?focusedCommentId=240615
`Payment successful` page for some reason is not cached in IE11. Refreshing or nagivating to this page by clicking `Back` redirects to `/vehicles/enter_details` (since `payment_id` was not found in session anymore) and breaks browser history
=> [CAZB-2893] Fix Pay for another vehicle back button in IE11

app/controllers/application_controller.rb, app/controllers/payments_controller.rb, spec/requests/payments_controller/index_spec.rb
https://eaflood.atlassian.net/browse/CAZB-2893
Govuk pay will now redirect to payment successful page with `id` query parameter. This allows `handle_history` to restore the session if new payment flow is started and user wants to come back to payment successful page
Manually on chrome and IE11, rspec updated
=> [CAZB-2893] Payment successful session handling fix for IE11

app/views/vehicles/country_input/_common.html.haml
Jira Card: https://eaflood.atlassian.net/browse/CAZB-4095
Safari:
=> [CAZB-4095] Safari browser the Continue button is overlapping on top of UK radio button in VRN entry page

Dockerfile.build, Dockerfile.test, Gemfile.lock
Recently there was a lot of drama around mimemagic gem - at first
mimemagic updated its licence to GPL2 to comply with its dependency
(freedesktop.org.xml) licence. In the process they yanked all
<0.3.6 licences and broke many builds (including ours) as 0.3.4
was direct dependency of Rails.
We have updated our Gemfile.lock to 0.3.6 to get our builds back
to green. This was yesterday. As of Today it looks like mimemagic
changed the owner. New owner extracted freedesktop.org.xml to be an outside
dependency, restored previous MIT licence, and again yanked all versions
<0.3.9 which again broke our build.
This commit bumps version to the closest available. We sincerely hope
we will not have to bump it again tomorrow.
If your build fails, please look at …
=> Bump mimemagic to 0.3.6
