app/controllers/vehicles_controller.rb
app/views/vehicles/confirm_details.html.haml
app/views/vehicles/incorrect_details.html.haml
app/views/vehicles/local_authority.html.haml
config/routes.rb
features/step_definitions/vehicle_steps.rb
features/vehicle.feature
spec/requests/vehicles_controller/local_authority_spec.rb

[JIRA](https://eaflood.atlassian.net/browse/CAZ-1141)

[CAZ-1141] Create incorrect details page

---

app/views/vehicles/country_input/_normal.html.haml
app/views/vehicles/details.html.haml
features/vehicles.feature

[JIRA](https://eaflood.atlassian.net/browse/CAZ-1140)

[CAZ-1140] Create confirm vehicle details page

---

app/controllers/refunds_controller.rb
app/views/non_uk_vehicles/choose_type.html.haml
app/views/non_uk_vehicles/index.html.haml
app/views/refunds/details.html.haml
app/views/refunds/scenarios.html.haml
app/views/vehicles/enter_details.html.haml
app/views/vehicles/incorrect_details.html.haml
app/views/welcome/index.html.haml
config/routes.rb
features/step_definitions/helper_steps.rb
features/vehicles.feature
spec/requests/non_uk_vehicles_controller/confirm_registration_spec.rb
spec/requests/refunds_controller_spec.rb

[JIRA](https://eaflood.atlassian.net/browse/CAZ-1142)
Create refund-scenarios page

[CAZ-1142] Create refund-scenarios page

---

app/controllers/vehicles_controller.rb
app/models/vrn_form.rb
app/views/vehicles/enter_details.html.haml
spec/models/vrn_form_spec.rb
spec/support/shared_examples/invalid_country_input.rb
spec/support/shared_examples/invalid_vrn_input.rb

As the next forms may be more difficult, I decided to use some library to serialize validations. Reform requires some model, so I decided to go with `ActiveModel::Validations`
I refactored `VrnForm` and related controller and view.

[NT] Refactor VrnForm

---

app/controllers/vehicles_controller.rb
app/models/confirmation_form.rb
spec/models/confirmation_form_spec.rb

I refactored `ConfirmationForm` same as `VrnForm`

[NT] Refactor ConfirmationForm

---

Gemfile
Gemfile.lock
app/api_wrapper/api_exception.rb
app/api_wrapper/base_api.rb
app/api_wrapper/compliance_checker_api.rb
app/api_wrapper/mock_vrn_response.rb
app/controllers/vehicles_controller.rb
app/models/vehicle_details.rb
app/services/base_service.rb
app/services/vrn_parser.rb
app/views/vehicles/details.html.haml
app/views/vehicles/unrecognised_vehicle.html.haml
config/routes.rb

[JIRA](https://eaflood.atlassian.net/browse/VCCS-556)

[CAZ-1156] Create unrecognised vehicle

---

app/controllers/application_controller.rb
config/routes.rb
spec/requests/application_controller_spec.rb

I added `build_id` endpoint as in other projects

[NT] Add build_id endpoint

---

app/controllers/vehicles_controller.rb
app/views/vehicles/compliant.html.haml
features/step_definitions/vehicle_steps.rb
features/vehicles.feature
spec/requests/vehicles_controller/complaint_spec.rb

[JIRA](https://eaflood.atlassian.net/browse/CAZ-1157)
Add  create compliant vehicle page

[CAZ-1157] Create compliant vehicle page

---

app/api_wrapper/compliance_checker_api.rb
app/api_wrapper/mock_compliance_response.rb
app/controllers/charges_controller.rb
app/models/compliance_details.rb
app/views/charges/daily_charge.html.haml
config/brakeman.ignore
config/locales/en.yml
config/routes.rb
features/charges.feature
features/step_definitions/charges_steps.rb
features/step_definitions/path_expectations.rb
features/support/mock_helper.rb
features/support/session_helper.rb
spec/fixtures/files/vehicle_compliance_response.json
spec/models/compliane_details_spec.rb
spec/rails_helper.rb
spec/requests/charges_controller/confirm_daily_charge_spec.rb
spec/requests/charges_controller/daily_charges_spec.rb
spec/requests/charges_controller/submit_local_authority_spec.rb
spec/support/add_vrn_to_session.rb

https://eaflood.atlassian.net/browse/CAZ-1154
I added a page as in the card with tests and mocks.

[CAZ-1154] Add daily charge page

---

app/views/vehicles/unrecognised.html.haml
package.json
yarn.lock

[JIRA](https://eaflood.atlassian.net/browse/CAZ-1156)

[CAZ-1156] Show real VRN value

---

app/views/layouts/_google_analytics.html.erb

[JIRA](https://eaflood.atlassian.net/browse/CAZ-1214)
Same changes as for [VCCS](https://github.com/InformedSolutions/JAQU-CAZ-Vehicle-Compliance-Checker-Web/pull/135)
[LINK](https://github.com/InformedSolutions/JAQU-CAZ-Vehicle-Compliance-Checker-Web/pull/135)

[CAZ-1214] Disable IP Tracking for Google Analytics

---

app/views/charges/_one_zone.html.haml
app/views/charges/local_authority.html.haml

https://eaflood.atlassian.net/browse/CAZ-1153 - second comment
I added if statement to determine whether to print this information or not.
Use `ABC123` and other VRN to test the difference

[CAZ-1153] Fix one zone information

---

app/controllers/charges_controller.rb
app/models/dates.rb
app/views/charges/daily_charge.html.haml
app/views/charges/dates.html.haml
app/views/charges/review_payment.html.haml
config/routes.rb
features/charges.feature
features/step_definitions/charges_steps.rb
features/step_definitions/path_expectations.rb
spec/models/dates_spec.rb
spec/requests/charges_controller/confirm_dates_spec.rb
spec/requests/charges_controller/dates_spec.rb

[JIRA](https://eaflood.atlassian.net/browse/CAZ-1155)
Add select date page

[CAZ-1155] Add select date page

---

.env.example
app/api_wrapper/compliance_checker_api.rb
app/views/vehicles/compliant.html.haml
config/application.rb

[JIRA](https://eaflood.atlassian.net/browse/CAZ-1157)

[NT] Add configurable link to Vehicle Checker

---

.drone.yml

Move to drone multi-pipeline

---

app/controllers/application_controller.rb
app/controllers/vehicles_controller.rb
features/support/session_helper.rb
spec/requests/vehicles_controller/submit_details_spec.rb

Fixes for CAZ-1221 and CAZ-1223
I decided to move all vehicle-related data to a common hash in the session, to make it easier to manage.

[NT] Rework storing vehicle details

---

app/controllers/vehicles_controller.rb

[NT] Remove spaces from VRN

---

app/views/welcome/index.html.haml

https://eaflood.atlassian.net/browse/CAZ-1282

[CAZ-1282] Update content on the welcome page

---

app/controllers/application_controller.rb
app/controllers/charges_controller.rb
app/controllers/non_uk_vehicles_controller.rb
app/controllers/vehicles_controller.rb
app/views/charges/dates.html.haml
app/views/vehicles/compliant.html.haml
app/views/vehicles/enter_details.html.haml
config/brakeman.ignore
features/charges.feature
features/step_definitions/charges_steps.rb
features/step_definitions/non_uk_vehicles_steps.rb
features/step_definitions/vehicle_steps.rb
features/support/session_helper.rb
features/vehicles.feature
spec/requests/charges_controller/submit_local_authority_spec.rb

[JIRA](https://eaflood.atlassian.net/browse/CAZ-1223)
Add back button logic.

[CAZ-1223] Fix the back button functionality

---

app/models/dates.rb
config/brakeman.ignore
spec/models/dates_spec.rb

…today, 6 future)
[JIRA](https://eaflood.atlassian.net/browse/CAZ-1279)

[CAZ-1279] Restrict dates selection to 13 days

---

app/views/charges/dates.html.haml

[JIRA](https://eaflood.atlassian.net/browse/CAZ-1279?focusedCommentId=163690&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-163690)

[CAZ-1279] Update text for dates page

---

app/api_wrapper/api_exception.rb

AWS exception has a `message` field is capitalized

[NT] Fix parsing AWS exceptions

---

app/api_wrapper/payments_api.rb
app/controllers/payments_controller.rb
app/models/payment.rb
config/environments/development.rb
config/environments/test.rb
spec/api_wrappers/payments_api/create_payment_spec.rb
spec/models/payment_spec.rb
spec/requests/payments_controller/create_spec.rb

I moved generating the return URL from service to controller.

[CAZ-1229] Fix passing return URL

---

app/api_wrapper/payments_api.rb

[CAZ-1229] Add days to log

---

app/api_wrapper/payments_api.rb
app/controllers/charges_controller.rb
app/controllers/payments_controller.rb
app/helpers/application_helper.rb
app/javascript/packs/application.js
app/javascript/src/printLink/init.js
app/models/payment.rb
app/views/charges/review_payment.html.haml
app/views/payments/confirm_payment.html.haml
config/routes.rb
features/payments.feature
features/step_definitions/path_expectations.rb
spec/models/payment_spec.rb
spec/requests/payments_controller/confirm_payment_spec.rb
spec/requests/payments_controller/create_spec.rb
spec/support/add_vrn_to_session.rb

[JIRA](https://eaflood.atlassian.net/browse/CAZ-1305)

[CAZ-1305] Create confirm payment page

---

app/views/charges/local_authority.html.haml
features/charges.feature

[JIRA](https://eaflood.atlassian.net/browse/CAZ-1222)
Add error summary to local authority page

[CAZ-1222] Add error summary to local authority page

---

app/api_wrapper/payments_api.rb

Adding missing docs.
Docs plus small refactoring

[NT] Add docs to PaymentsApi.payment_status

---

app/models/compliance_details.rb
app/views/charges/daily_charge.html.haml
spec/models/compliance_details_spec.rb
spec/requests/charges_controller/daily_charges_spec.rb

https://eaflood.atlassian.net/browse/CAZ-1340
Added link with a method in the model. Fixed some tests.

[CAZ-1340] Add become compliant link

---

app/javascript/styles/related_components.scss

[NT] Refactoring related components scss

---

app/views/charges/review_payment.html.haml

https://eaflood.atlassian.net/browse/CAZ-1434
Just added IDs

[CAZ-1434] Add IDs to review page

---

app/views/charges/local_authority.html.haml
app/views/common/_error_summary.html.haml
app/views/dates/daily_charge.html.haml
app/views/dates/select_daily_date.html.haml
app/views/dates/select_period.html.haml
app/views/dates/select_period_input/_errored.html.haml
app/views/dates/select_weekly_date.html.haml
app/views/dates/weekly_charge.html.haml
app/views/non_dvla_vehicles/choose_type.html.haml
app/views/non_dvla_vehicles/index.html.haml
app/views/vehicles/details.html.haml
app/views/vehicles/unrecognised.html.haml
features/vehicles.feature

[JIRA](https://eaflood.atlassian.net/browse/CAZ-1139)

[CAZ-1139] Refactoring error summary and add to choose type, non dvla and unrecognised pages

---

app/controllers/charges_controller.rb
app/helpers/application_helper.rb
app/views/charges/review_payment.html.haml
app/views/dates/select_daily_date.html.haml
features/charges.feature
features/step_definitions/charges_steps.rb
features/step_definitions/path_expectations.rb
features/support/session_helper.rb

[JIRA](https://eaflood.atlassian.net/browse/CAZ-1317)
URL path should be dynamic depends on which period was selected(daily or weekly)

[CAZ-1317] Fix payment for link on review payment page

---

.drone.yml
app/assets/stylesheets/application.scss

Restored this file as maybe it is needed
Also added js linter

[NT] Restore application.scss file (for rails assets:precompile)

---

.drone.yml

IMplemented end to end tests

---

.drone.yml
.scss-lint.yml
Gemfile
Gemfile.lock
README.md
app/javascript/src/cookiesBanner/styles.scss
app/javascript/styles/application.scss

https://docs.publishing.service.gov.uk/manual/migrate-from-govuk-lint.html

[NT] Replace scss linter

---

.env.example
.github/PULL_REQUEST_TEMPLATE
.rubocop.yml
app/api_wrapper/api_exception.rb
app/api_wrapper/compliance_checker_api.rb
app/controllers/application_controller.rb
app/javascript/packs/application.js
app/javascript/src/cookiesBanner/init.js
app/javascript/src/cookiesBanner/styles.scss
app/javascript/src/printLink/init.js
app/javascript/src/printLink/styles.scss
app/views/layouts/_cookies_banner.haml
app/views/layouts/_google_analytics.html.erb
app/views/layouts/application.html.haml
app/views/payments/success.html.haml
config/application.rb
config/environments/production.rb
config/initializers/content_security_policy.rb
config/webpack/environment.js

[JIRA](https://eaflood.atlassian.net/browse/CAZ-1488)

[CAZ-1488] Add Basic AUTH

---

app/views/vehicles/compliant.html.haml

[JIRA](https://eaflood.atlassian.net/browse/CAZ-1443)

[CAZ-1443] Fix back button

---

app/views/welcome/index.html.haml

[JIRA](https://eaflood.atlassian.net/browse/CAZ-1490)

[CAZ-1490] Update start page content

---

app/services/session_manipulation/set_leeds_taxi.rb

[NT] Fix docs

---

app/controllers/application_controller.rb
app/controllers/charges_controller.rb
app/controllers/payments_controller.rb
app/controllers/vehicles_controller.rb
app/views/vehicles/_compliant_and_exempt.html.haml
app/views/vehicles/compliant.html.haml
app/views/vehicles/exempt.html.haml
config/routes.rb
features/step_definitions/vehicle_steps.rb
features/support/mock_helper.rb
features/vehicles.feature
sonar-project.properties
spec/fixtures/files/vehicle_details_exempt_response.json
spec/requests/vehicles_controller/details_spec.rb
spec/requests/vehicles_controller/exempt_spec.rb

[JIRA](https://eaflood.atlassian.net/browse/CAZ-1443)

[CAZ-1443] Fix back button on exempt page

---

app/services/vehicle_types.rb
spec/services/vehicle_types_spec.rb

The taxi should not be a selected type, it should come from NTR.

[NT] Remove Taxi from types

---

.drone.yml

Updated drone file for SIT environment

---

.drone.yml

Corrected line indentation for SIT env drone steps

---

app/services/vehicle_types.rb

[NT] Fix rubocop warning

---

app/controllers/application_controller.rb

[NT] Skip basic auth for build id

---

config/initializers/content_security_policy.rb
config/initializers/session_store.rb
yarn.lock

[JIRA](https://eaflood.atlassian.net/browse/CAZ-1495)

[CAZ-1495] Add CSP policy

---

app/views/charges/local_authority.html.haml
app/views/dates/daily_charge.html.haml
app/views/dates/select_daily_date.html.haml
app/views/dates/select_period.html.haml
app/views/dates/select_weekly_date.html.haml
app/views/dates/weekly_charge.html.haml
app/views/non_dvla_vehicles/choose_type.html.haml
app/views/non_dvla_vehicles/index.html.haml
app/views/vehicles/details.html.haml
app/views/vehicles/enter_details.html.haml
app/views/vehicles/unrecognised.html.haml

[JIRA](https://eaflood.atlassian.net/browse/CAZ-1498)
I fixed pa11y tests based on Edmont's [mr](https://github.com/InformedSolutions/JAQU-CAZ-Payments-UI/pull/99/files)

[CAZ-1498] Fix pa11y tests

---

.drone.yml

Feature/caz 1182/nightly ci builds

---

.drone.yml

Updated Payments GA tracking id

---

app/controllers/application_controller.rb
config/routes.rb

[NT] Add health endpoint and skip basic auth

---

spec/support/add_to_session.rb

[NT] Refactor add to session method

---

app/javascript/styles/application.scss
app/views/vehicles/vrn_input/_errored.html.haml
app/views/vehicles/vrn_input/_normal.html.haml

[JIRA](https://eaflood.atlassian.net/browse/CAZ-1495)

[CAZ-1492] Fix inline style error

---

app/helpers/application_helper.rb
app/views/dates/daily_charge.html.haml
app/views/dates/weekly_charge.html.haml
app/views/layouts/_feedback_section.html.haml
app/views/vehicles/_compliant_and_exempt.html.haml
app/views/vehicles/incorrect_details.html.haml
app/views/vehicles/unrecognised.html.haml
app/views/welcome/index.html.haml
config/locales/en.yml

https://www.w3.org/WAI/GL/wiki/Using_aria-label_for_link_purpose
Added a helper to wrap external links with area-label, blank target

[NT] Add external link helper

---

.drone.yml

Ammended Payments URL and implemented test on pull request

---

.drone.yml

Implemented ZAP tests for nightly run

---

app/javascript/src/printLink/init.js
app/javascript/src/printLink/styles.scss
app/views/common/_print_link.haml
app/views/payments/success.html.haml

https://eaflood.atlassian.net/browse/CAZ-1615
To make it consistent with Wave I replaced the link with button and removed custom styles.

[CAZ-1615] Fix print link

---

.drone.yml

[NT] Add bundle exec command to drone.yml

---

.drone.yml

fixed accessibility tests

---

.env.example
app/views/welcome/index.html.haml
config/application.rb
yarn.lock

https://eaflood.atlassian.net/browse/CAZ-1632

[CAZ-1632] Add fleets links

---

app/views/dates/daily_charge.html.haml
app/views/dates/select_daily_date.html.haml
app/views/dates/select_period.html.haml
app/views/dates/select_weekly_date.html.haml
app/views/dates/weekly_charge.html.haml
features/charges.feature
features/taxi.feature
spec/requests/dates_controller/weekly_charges_spec.rb

[CAZ- 1684-1688] Update content

---

app/helpers/application_helper.rb
config/locales/en.yml
features/charges.feature
pa11y/.pa11yci.conf.js

- Redirect to 'Choose your dates' page from 'Review' page.
- Update validation error message for Vehicle Registration format error.

Redirect to Date Selection page from Payment Review

---

app/views/dates/daily_charge.html.haml
app/views/dates/weekly_charge.html.haml

Corrects the grammar of a sentence on the exemption page and aligns the content of the Leeds Taxi Weekly exemption page with the happy path page.

Correct typo and align exemption page content

---

app/api_wrapper/payments_api.rb
app/models/compliance_details.rb
app/models/payment.rb
app/services/session_manipulation/base_manipulator.rb
app/services/session_manipulation/set_compliance_details.rb
spec/api_wrappers/compliance_checker_api/vehicle_compliance_spec.rb
spec/api_wrappers/payments_api/create_payment_spec.rb
spec/fixtures/files/vehicle_compliance_birmingham_response.json
spec/fixtures/files/vehicle_compliance_leeds_response.json
spec/fixtures/files/vehicle_compliance_many_charges_response.json
spec/fixtures/files/vehicle_compliance_one_charge_response.json
spec/fixtures/files/vehicle_compliance_with_zero_charge_response.json
spec/models/compliance_details_spec.rb
spec/models/payment_spec.rb
spec/requests/charges_controller/submit_local_authority_spec.rb
spec/services/session_manipulation/set_compliance_details_spec.rb
spec/support/shared_examples/compliance_details_fields.rb

https://eaflood.atlassian.net/browse/CAZ-1730
Don't merge before changes in the backend. We need to confirm that it is actually working

[CAZ-1730] Add tariff code

---

app/services/session_manipulation/base_manipulator.rb
app/services/session_manipulation/calculate_total_charge.rb
app/services/session_manipulation/set_chargeable_zones.rb
app/services/session_manipulation/set_compliance_details.rb
app/services/session_manipulation/set_payment_id.rb
app/services/session_manipulation/set_user_email.rb
spec/services/session_manipulation/set_chargeable_zones_spec.rb

There was an issue with non-UK flow that setting chargeable_zones cleared the vehicle type.

[NT] Fix non-UK flow

---

pa11y/.pa11yci.conf.js

pa11y fixes

---

.drone.yml

removed pull request for accessibility tests, and end to end tests from dev push

removed steps from build

---

app/controllers/vehicles_controller.rb
app/views/non_dvla_vehicles/index.html.haml
app/views/vehicles/enter_details.html.haml
features/vehicles.feature
spec/rails_helper.rb

[CAZ-1239](https://eaflood.atlassian.net/browse/CAZ-1239)

[CAZ-1239] Add check another vehicle link on non-uk page

---

.drone.yml
.rubocop.yml
package.json
yarn.lock

[NT] Use yarn exclude 961 unless fix will be released

---

.drone.yml

Correct SIT brakeman command

---

Dockerfile.build
Dockerfile.test

[NT] Update docker image version

---

app/api_wrapper/base_api.rb
app/api_wrapper/compliance_checker_api.rb
app/api_wrapper/payments_api.rb
app/controllers/payments_controller.rb
app/models/compliance_details.rb
app/models/payment_details.rb
app/views/dates/daily_charge.html.haml
app/views/payments/failure.html.haml
app/views/payments/success.html.haml
features/step_definitions/payments_steps.rb
spec/models/compliance_details_spec.rb
spec/models/payment_details_spec.rb
spec/requests/dates_controller/daily_charges_spec.rb
spec/requests/payments_controller/success_spec.rb
spec/services/session_manipulation/set_payment_details_spec.rb
yarn.lock

https://eaflood.atlassian.net/browse/CAZ-1612

[CAZ-1612] Add links

---

.drone.yml

Added full build name for BrowserStack

---

app/api_wrapper/payments_api.rb

The app was crushing as there is no backend API yet.

[CAZ-1761] [FIX] Rescue DPP error

---

.drone.yml

Add drone steps for new ST environment

[CI SKIP] Add drone steps for new ST environment

---

app/controllers/dates_controller.rb
app/helpers/dates_helper.rb
app/services/dates/base.rb
app/services/dates/check_paid_daily.rb
app/services/dates/check_paid_weekly.rb
app/services/dates/daily.rb
app/services/dates/weekly.rb
app/views/dates/select_daily_date.html.haml
app/views/dates/select_weekly_date.html.haml
config/locales/en.yml
features/charges.feature
features/step_definitions/charges_steps.rb
features/step_definitions/taxi_steps.rb
features/support/session_helper.rb
features/taxi.feature
spec/helpers/dates_helper_spec.rb
spec/requests/dates_controller/confirm_date_weekly_spec.rb
spec/requests/dates_controller/select_date_weekly_spec.rb
spec/services/dates/check_paid_weekly_spec.rb
spec/services/dates/weekly_spec.rb

https://eaflood.atlassian.net/browse/CAZ-1776

[CAZ-1776] Add weekly double payment prevention

---

config/locales/en.yml
features/taxi.feature

[NT] Change error messages for DPP

---

app/views/non_dvla_vehicles/index.html.haml
app/views/vehicles/unrecognised.html.haml
config/locales/en.yml
features/step_definitions/vehicle_steps.rb
features/vehicles.feature

https://eaflood.atlassian.net/browse/CAZ-1908
https://eaflood.atlassian.net/browse/CAZ-1909

[CAZ-1908] [CAZ-1909] Change content

---

app/views/welcome/index.html.haml
features/refunds.feature
features/step_definitions/welcome_steps.rb

https://eaflood.atlassian.net/browse/CAZ-1905

[CAZ-1905] Change start page content

---

app/views/welcome/index.html.haml

[NT] Fix external link

---

app/controllers/accessibility_controller.rb
app/views/accessibility/index.html.haml
app/views/charges/local_authority.html.haml
app/views/charges/review_payment.html.haml
app/views/common/_draft_tag.html.haml
app/views/dates/daily_charge.html.haml
app/views/dates/select_daily_date.html.haml
app/views/dates/select_period.html.haml
app/views/dates/select_weekly_date.html.haml
app/views/dates/weekly_charge.html.haml
app/views/layouts/_footer.html.haml
app/views/non_dvla_vehicles/choose_type.html.haml
app/views/non_dvla_vehicles/index.html.haml
app/views/payments/failure.html.haml
app/views/payments/index.html.haml
app/views/payments/success.html.haml
app/views/refunds/details.html.haml
app/views/refunds/scenarios.html.haml
app/views/vehicles/_compliant_and_exempt.html.haml
app/views/vehicles/details.html.haml
app/views/vehicles/enter_details.html.haml
app/views/vehicles/incorrect_details.html.haml
app/views/vehicles/unrecognised.html.haml
app/views/welcome/index.html.haml
config/routes.rb
features/accessibility.feature
features/step_definitions/helper_steps.rb
features/vehicles.feature

- CAZ-1896: H1 change
- CAZ-1897: change date alignment
- CAZ-1898: add accessibility statement
- CAZ-1899: non-DVLA vehicle 'choose type' text change
- CAZ-1917: remove draft content label

V1 content changes

---

Gemfile
Gemfile.lock
app/api_wrapper/payments_api.rb
app/controllers/cookies_controller.rb
app/views/cookies/_ga.html.haml
app/views/cookies/_seen_message.html.haml
app/views/cookies/_session.html.haml
app/views/cookies/_table_head.html.haml
app/views/cookies/index.html.haml
app/views/layouts/_cookies_banner.haml
app/views/layouts/_footer.html.haml
config/initializers/session_store.rb
config/routes.rb
features/cookies.feature
features/step_definitions/path_expectations.rb
spec/requests/cookies_controller_spec.rb

https://eaflood.atlassian.net/browse/CAZ-1912

[CAZ-1912] Add cookies page

---

app/controllers/policies_controller.rb
app/views/layouts/_footer.html.haml
app/views/policies/index.html.haml
config/routes.rb
features/privacy_notice.feature
features/step_definitions/path_expectations.rb
spec/requests/policies_controller_spec.rb

https://eaflood.atlassian.net/browse/CAZ-1913

[CAZ-1913] Add privacy notice page

---

additional_url.yml
app/models/compliance_details.rb
app/views/dates/daily_charge.html.haml
app/views/payments/success.html.haml
spec/models/compliance_details_spec.rb
spec/requests/dates_controller/daily_charges_spec.rb
spec/requests/payments_controller/success_spec.rb

https://eaflood.atlassian.net/browse/CAZ-1910
https://eaflood.atlassian.net/browse/CAZ-1911

[CAZ-1910] [CAZ-1911] Add dynamic compliance link

---

app/views/accessibility/index.html.haml

Correct accessibility statement

---

app/views/payments/failure.html.haml
features/payments.feature
features/step_definitions/path_expectations.rb

Update payment unsuccessful page

---

app/views/charges/local_authority.html.haml
app/views/dates/select_period.html.haml
app/views/dates/select_period_input/_errored.html.haml
config/locales/en.yml
features/charges.feature
features/taxi.feature
features/vehicles.feature
spec/models/confirmation_form_spec.rb

[CAZ-1882] Error message review changes

---

app/views/payments/failure.html.haml
app/views/payments/success.html.haml

Update ST with content fixes

---

app/views/cookies/_ga.html.haml
app/views/cookies/_session.html.haml

https://eaflood.atlassian.net/browse/CAZ-1912

[CAZ-1912] [Fix] Fix cookie page

---

app/views/cookies/_ga.html.haml

Correct _gat expiration period

---

app/models/compliance_details.rb
app/views/cookies/_ga.html.haml
app/views/cookies/_session.html.haml
spec/models/compliance_details_spec.rb

Update ST with latest UI code

---

app/views/non_dvla_vehicles/index.html.haml

[CAZ-1908] Correct wording for non-uk page

---

additional_url.yml
app/controllers/vehicles_controller.rb
app/models/compliance_details.rb
app/services/session_manipulation/base_manipulator.rb
app/services/session_manipulation/calculate_total_charge.rb
app/services/session_manipulation/clear_payment_details.rb
app/services/session_manipulation/set_chargeable_zones.rb
app/services/session_manipulation/set_compliance_details.rb
app/services/session_manipulation/set_incorrect.rb
app/services/session_manipulation/set_payment_details.rb
app/services/session_manipulation/set_payment_id.rb
app/views/payments/success.html.haml
spec/models/compliance_details_spec.rb
spec/requests/vehicles_controller/details_spec.rb
spec/services/session_manipulation/clear_payment_details_spec.rb

https://eaflood.atlassian.net/browse/CAZ-1910
https://eaflood.atlassian.net/browse/CAZ-1911
Dynamic links will both come from additional_url.yml file. 
Birmingham car will be determined by saved in the session type, as TAXI overrides the type in the tariff code.

[FIX] [CAZ-1910] [CAZ-1911] Fix dynamic link

---

additional_url.yml
app/controllers/vehicles_controller.rb
app/models/compliance_details.rb
app/models/vrn_form.rb
app/services/session_manipulation/base_manipulator.rb
app/services/session_manipulation/calculate_total_charge.rb
app/services/session_manipulation/clear_payment_details.rb
app/services/session_manipulation/set_chargeable_zones.rb
app/services/session_manipulation/set_compliance_details.rb
app/services/session_manipulation/set_incorrect.rb
app/services/session_manipulation/set_payment_details.rb
app/services/session_manipulation/set_payment_id.rb
app/views/non_dvla_vehicles/index.html.haml
app/views/payments/success.html.haml
spec/models/compliance_details_spec.rb
spec/models/vrn_form_spec.rb
spec/requests/vehicles_controller/details_spec.rb
spec/services/session_manipulation/clear_payment_details_spec.rb

Update ST with latest material from Sprint 9

Update ST with latest material from Sprint 9

---

.drone.yml

Changed browser set to new basic auth title

---

app/controllers/dates_controller.rb
app/views/dates/daily/_all_paid.html.haml
app/views/dates/select_daily_date.html.haml
app/views/dates/select_weekly_date.html.haml

Hide continue button and show message if no dates can be paid for

---

features/charges.feature
features/step_definitions/charges_steps.rb

Added tests for ending payment journey if no more dates can be paid for

---

app/services/dates/weekly.rb
spec/services/dates/weekly_spec.rb

The payment window for Leeds taxi drivers to buy a weekly pass needs to be expanded from 8 days to 13.

Expand leeds taxi weekly pass payment window to 13 days

---

app/services/dates/weekly.rb
features/charges.feature
features/step_definitions/charges_steps.rb
spec/services/dates/weekly_spec.rb

Update ST with release candidate v0.2.0 (including Leeds window update)

Update ST with release candidate v0.2.0

---

app/api_wrapper/payments_api.rb
app/models/payment.rb
spec/api_wrappers/payments_api/create_payment_spec.rb
spec/models/payment_spec.rb

[JIRA](https://eaflood.atlassian.net/browse/CAZ-1873)

[Do not merge][WIP][CAZ-1873] Rework payment creation

---

app/models/payment.rb
spec/models/payment_spec.rb

[NT] Convert charge in pence

---

app/views/payments/success.html.haml

Separate dates on to separate lines on success page

---

app/controllers/dates_controller.rb

[NT] Add small refactoring

---

.env.example
config/environments/production.rb
config/initializers/content_security_policy.rb

https://eaflood.atlassian.net/browse/CAZ-1955

[CAZ-1955] Add Cloudfront integration

---

.drone.yml

removed microperf

---

app/views/cookies/_cookie_control.html.haml
app/views/cookies/_seen_message.html.haml
app/views/cookies/index.html.haml

[JIRA](https://eaflood.atlassian.net/browse/CAZB-585)

[CAZB-585] Update cookies page

---

Gemfile
Gemfile.lock
app/views/cookies/_cookie_control.html.haml
app/views/cookies/_ga.html.haml
app/views/cookies/_session.html.haml
app/views/cookies/index.html.haml
app/views/layouts/_cookie_control.html.erb

[JIRA](https://eaflood.atlassian.net/browse/CAZB-641)

[CAZB-641] Content change to NTR Cookie Policy

---

.drone.yml

CAZ-2054 Feature/caz 2054/prod drone changes

---

config/application.rb
config/environments/production.rb
config/log_format.rb

[CAZSM-9] Removal of ip addresses from application logs

---

config/application.rb
config/environments/production.rb
config/log_format.rb

* edited logging
* fixed extra line

[CAZSM-9] Removal of ip addresses from application logs (#201)

---

app/views/layouts/_cookie_control.html.erb

[CAZB-641] `Accept all cookies` button enabled GA cookies by default

---

app/views/layouts/_cookie_control.html.erb
pa11y/.pa11yci.conf.js

https://eaflood.atlassian.net/browse/CAZB-742

[CAZB-742] Hide Control Cookie buttons and add `Save and close` button

---

pa11y/.pa11yci.conf.js

[NT] Remove `screen capture` from pa11y tests

---

config/environments/production.rb

Remove require `logstash-logger` from production.rb

---

app/javascript/packs/application.js
app/javascript/src/printLink/init.js
app/javascript/src/printLink/styles.scss
app/views/common/_print_link.haml

Fix print link on success page

Fix print link on success page

---

.drone.yml

CAZ-2143 updated drone file with to retrieve from awssecrets

---

app/helpers/dates_helper.rb

Make today not paid check method private

---

app/views/dates/weekly_charge.html.haml

update will -> may

---

app/javascript/styles/cookie_control.scss
app/views/layouts/_cookie_control.html.erb
app/views/layouts/application.html.haml

https://eaflood.atlassian.net/browse/CAZ-2242
Note: No more line break for `introText`

[CAZ-2242] Add `sameSiteCookie` to Cookie Control config

---

app/views/layouts/_cookie_control.html.erb
yarn.lock

Trying to fix firefox bug when CC duplicated with different domain names:
- .paycleanairzonecharge.co.uk
- .dev.paycleanairzonecharge.co.uk
---------------------------------------

[CAZ-2242] Add `subDomains` option to cookie control config

---

app/javascript/src/cookieControl.js

https://eaflood.atlassian.net/browse/CAZ-CAZ-2242
Avoid showing the cookie control modal page after the redirect from govuk.pay

[CAZ-CAZ-2242] Set secure flag for Cookie Control

---

app/javascript/src/cookieControl.js

revert [CAZ-2242] Set secure flag for ControlCookie (#225)

---

.drone.yml

Add retry for yarn audit

---

app/views/payments/failure.html.haml

Add payment unsuccessful page content

---

app/views/payments/failure.html.haml
features/payments.feature

Combine content on payment unsuccessful page

---

.drone.yml
app/controllers/application_controller.rb
app/controllers/dates_controller.rb
app/controllers/payments_controller.rb
app/controllers/welcome_controller.rb
app/javascript/src/cookieControl.js
app/javascript/styles/cookie_control.scss
app/services/session_manipulation/clear_session_details.rb
app/views/layouts/_cookie_control.html.erb
app/views/layouts/application.html.haml
app/views/payments/failure.html.haml
features/payments.feature
features/step_definitions/payments_steps.rb
spec/requests/welcome_controller_spec.rb
spec/services/session_manipulation/clear_session_details_spec.rb
yarn.lock

Re-release v1.0.0 to ST

---

.drone.yml

add drone configuration for UAT environment (#233)

---

.drone.yml

Git ssh key fix for drone file

Git ssh key fix for drone file

---

app/views/vehicles/country_input/_normal.html.haml

Jira card: https://eaflood.atlassian.net/browse/CAZ-2278

[CAZ-2278] Fixes missing fieldset with label for screen readers

---

app/views/dates/daily_charge.html.haml
app/views/dates/weekly_charge.html.haml
app/views/payments/success.html.haml

Jira card: https://eaflood.atlassian.net/browse/CAZ-2185
Updated links text
I tried to make a payment.

[CAZ-2185] Change links tests

---

app/helpers/application_helper.rb
app/views/charges/local_authority.html.haml
app/views/charges/review_payment.html.haml
app/views/dates/daily_charge.html.haml
app/views/dates/select_daily_date.html.haml
app/views/dates/select_period.html.haml
app/views/dates/select_weekly_date.html.haml
app/views/errors/internal_server_error.html.haml
app/views/non_dvla_vehicles/choose_type.html.haml
app/views/non_dvla_vehicles/index.html.haml
app/views/payments/failure.html.haml
app/views/payments/success.html.haml
app/views/static_pages/accessibility_statement.html.haml
app/views/static_pages/cookies.html.haml
app/views/static_pages/privacy_notice.html.haml
app/views/vehicles/details.html.haml
app/views/vehicles/enter_details.html.haml
app/views/vehicles/exempt.html.haml
app/views/vehicles/incorrect_details.html.haml
app/views/vehicles/unrecognised.html.haml
features/vehicles.feature

Jira card: https://eaflood.atlassian.net/browse/CAZ-2283
We need to have meaningful page titles. 
Updated the titles. 
I was not able to find 3 of the request pages: 
```
Payment in progress => Payment in progress | Pay a Clean Air Zone Charge
Declined => Payment declined | Pay a Clean Air Zone Charge
Session expired => Session expired | Pay a Clean Air Zone Charge
```
If you know how to find it it would be very helpful.

[CAZ-2283] Updated pages titles

---

app/javascript/src/printLink/init.js
app/javascript/src/printLink/styles.scss
app/views/common/_print_link.haml

Jira card: https://eaflood.atlassian.net/browse/CAZ-2279
`Print this page` link should be a real HTML link. 
Updated the link 
Tried to print page after successful payment

[CAZ-2279] Update print link to be a real link

---

app/views/payments/success.html.haml

https://eaflood.atlassian.net/browse/CAZ-2315
Update h1 -> h2 on success payment page. 
Try to make payment.

[CAZ-2315] Fix Heading Structure for Success payment page

---

app/views/charges/review_payment.html.haml

Jira card: https://eaflood.atlassian.net/browse/CAZ-2314
Added hidden text to non-descriptive links. 
Tried to make payment.

[CAZ-2314] Fix Non-descriptive links

---

app/views/layouts/application.html.haml

Jira card: https://eaflood.atlassian.net/browse/CAZ-2280
Finally, after my investigation, the only missing thing was the link which directs to `#main-content`

[CAZ-2280] Skip to Main Content link

---

app/views/charges/review_payment.html.haml
app/views/payments/success.html.haml
app/views/vehicles/details.html.haml

Jira card: https://eaflood.atlassian.net/browse/CAZ-2338
Updated table headers. 
Before: 
After:

[CAZ-2338] Fix tables headers

---

app/controllers/vehicles_controller.rb
app/views/vehicles/compliant.html.haml

Dynamic back link on compliance page

---

app/api_wrapper/compliance_checker_api.rb
app/models/vehicle_details.rb
spec/fixtures/files/vehicle_compliance_birmingham_response.json
spec/fixtures/files/vehicle_compliance_leeds_response.json
spec/fixtures/files/vehicle_compliance_many_charges_response.json
spec/fixtures/files/vehicle_compliance_one_charge_response.json
spec/fixtures/files/vehicle_compliance_with_zero_charge_response.json

Jira card: https://eaflood.atlassian.net/browse/CAZB-1183
Removed URLs from the docs and tests. 
N/A

[CAZB-1183] Removes urls from docs and tests

---

app/views/vehicles/compliant.html.haml
app/views/vehicles/exempt.html.haml
app/views/vehicles/unrecognised.html.haml
features/step_definitions/path_expectations.rb

Fixes [CAZ-2310](https://eaflood.atlassian.net/browse/CAZ-2310).

Add flag to back links

---

app/helpers/application_helper.rb

Jira card: https://eaflood.atlassian.net/browse/CAZ-2281
We need to display information that link opens in a new window for external links.

[CAZ-2281] add text to links which opens in a new window

---

app/views/dates/select_weekly_date.html.haml
features/charges.feature

Update all dates paid for content for weekly charge

---

features/step_definitions/vehicle_steps.rb
features/support/mock_helper.rb
features/vehicles.feature
pa11y/.pa11yci.conf.js

[CAZB-1160] Api call for non-uk exemption - integration specs

---

app/helpers/application_helper.rb

https://eaflood.atlassian.net/browse/CAZ-2281

[CAZ-2281] Remove aria-label from external links if not needed

---

app/controllers/charges_controller.rb
app/controllers/vehicles_controller.rb
app/views/vehicles/not_determined.html.haml
config/routes.rb
features/step_definitions/vehicle_steps.rb
features/support/mock_helper.rb
features/vehicles.feature
spec/requests/vehicles_controller/not_determined_spec.rb
spec/requests/vehicles_controller/submit_type_spec.rb

Jira card: https://eaflood.atlassian.net/browse/CAZ-2111
Vehicles, where we are not able to get compliance, should move to the page where user can provide vehicle type and go through the non_dvla process. 
Test vrns: 
```
{
"description": "Test case no EURO STATUS CAZ-2111",
"registrationNumber": "TST009",
"colour": "Black",
"typeApprovalCategory": "N3",
"make": "Mercedes-Benz",
"model": "Ciato",
"fuelType": "Diesel",
"expectedOutcomes": {
"type": "null",
"exempt": "null",
"compliant": "null"
}
},
{
"description": "Test case no fuel type CAZ-2111",
"registrationNumber": "TST010",
"colour": "Black",
"typeApprovalCategory": "N3",
"make": "Mercedes-Benz",
"model": "Ciato",
"euroStatus": "EURO V",
"expectedOutcomes": {
"type": "null",
"exempt": "null",
"compliant": "null"
}
},
{ …
```

[CAZ-2111] Handle Incomplete Vehicle details

---

app/api_wrapper/payments_api.rb
spec/api_wrappers/payments_api/create_payment_spec.rb

Jira card: https://eaflood.atlassian.net/browse/CAZ-2543
Support telephoneNumber for payment creation.

[CAZ-2543] Support telephonePayment params during payment creation

---

app/views/vehicles/enter_details.html.haml

https://eaflood.atlassian.net/browse/CAZ-2278

[CAZ-2278] Fix vrn form labels

---

app/controllers/dates_controller.rb
app/helpers/application_helper.rb
app/models/caz.rb
app/services/chargeable_zones_service.rb
app/services/dates/daily.rb
app/services/fetch_single_caz_data.rb
app/views/dates/daily/_details.html.haml
app/views/dates/select_weekly_date.html.haml
features/step_definitions/charges_steps.rb
features/support/mock_helper.rb
spec/models/caz_spec.rb
spec/requests/dates_controller/select_daily_date_spec.rb
spec/services/dates/daily_spec.rb

[Link to CAZ-2391 JIRA Card](https://eaflood.atlassian.net/browse/CAZ-2391)
* Filtering out dates before official charging activation date
* Updated copy on the listing dates page
Manually, rspec, cucumber

[CAZ-2391] Filtering out dates before charging start

---

app/helpers/dates_helper.rb
app/views/vehicles/incorrect_details.html.haml
features/vehicles.feature

Jira card: https://eaflood.atlassian.net/browse/CAZ-2111
Fixed the process of payment when paying for an undetermined/incomplete incorrect vehicle.
Added feature test.
Tested VRNs: [TST009, TST010, TST011, CAS309, CAS308]

[CAZ-2111] Fix Incorrect Undermined Vehicle process

---

app/views/layouts/_cookie_control.html.erb

https://eaflood.atlassian.net/browse/CAZB-1030

[CAZB-1033] Update CookieControl to version 9

---

app/views/vehicles/_compliant_and_exempt.html.haml

Update wording for compliant & exempt pages

---

package.json

Update packages to use rails 6.0.3

---

app/helpers/application_helper.rb
app/views/dates/daily_charge.html.haml
app/views/dates/weekly_charge.html.haml
app/views/layouts/_feedback_section.html.haml
app/views/layouts/_header.html.haml
app/views/payments/success.html.haml
app/views/static_pages/accessibility_statement.html.haml
app/views/static_pages/cookies.html.haml
app/views/static_pages/cookies/_ga.html.haml
app/views/static_pages/privacy_notice.html.haml
app/views/vehicles/_compliant_and_exempt.html.haml
app/views/vehicles/incorrect_details.html.haml
app/views/vehicles/unrecognised.html.haml
app/views/welcome/index.html.haml
config/environments/development.rb
config/locales/en.yml
yarn.lock

https://eaflood.atlassian.net/browse/CAZ-2575
Update all external links to match requirements from card description
Manually
n/a

[CAZ-2575] Update links behavior

---

app/views/layouts/_cookie_control.html.erb
yarn.lock

[CAZ-2282] Enable focus state indicator for civic cookie controller

---

app/views/layouts/_cookie_control.html.erb

Fix cookie control config format

---

app/views/layouts/application.html.haml

https://eaflood.atlassian.net/browse/CAZB-1507

[CAZB-1543] Update check sum for Cookie Controller

---

app/views/vehicles/_compliant_and_exempt.html.haml

[CAZ-2712] Update wording for compliant & exempt pages

---

Gemfile.lock
app/views/static_pages/privacy_notice.html.haml
features/static_pages.feature

https://eaflood.atlassian.net/browse/CAZ-2794

[CAZB-2794] IOD Privacy Notice

---

.rubocop.yml
app/api_wrapper/base_api.rb
app/api_wrapper/compliance_checker_api.rb
app/api_wrapper/payments_api.rb
app/controllers/dates_controller.rb
app/models/payment.rb
app/services/dates/base.rb
app/services/dates/daily.rb
app/services/dates/weekly.rb
app/services/fetch_single_caz_data.rb
app/views/dates/_weekly_details.html.haml
app/views/dates/select_daily_date.html.haml
app/views/dates/select_weekly_date.html.haml
config/initializers/webpacker.rb
features/charges.feature
features/step_definitions/charges_steps.rb
features/step_definitions/helper_steps.rb
features/step_definitions/taxi_steps.rb
features/taxi.feature
spec/api_wrappers/payments_api/create_payment_spec.rb
spec/models/payment_spec.rb
spec/requests/dates_controller/select_daily_date_spec.rb
spec/requests/dates_controller/select_weekly_date_spec.rb
spec/services/dates/daily_spec.rb
spec/services/dates/weekly_spec.rb

https://eaflood.atlassian.net/browse/CAZ-2810

[CAZ-2807] D-Day notice to not be displayed when does not apply

---

.drone.yml

Fix prod workspace selection for UI layer

Fix drone prod deploy step

---

.drone.yml

Fix drone prod deploy step (#285)

---

app/assets/stylesheets/application.css
app/javascript/styles/cookie_control.scss
app/views/layouts/_cookie_control.html.erb

[CAZ-2282] Override cookie CSS to add focus

---

app/views/static_pages/privacy_notice.html.haml

[CAZ-2820] amend links in privacy notice

---

.drone2.yml

updated secrets and account name

---

.drone2.yml

issue fixed -account_name

---

Gemfile.lock
app/controllers/payments_controller.rb
spec/requests/payments_controller/create_spec.rb

[CAZ-2611] create new payment from review page unconditionally

---

.drone2.yml

ST step fixes

---

app/helpers/application_helper.rb
app/views/layouts/application.html.haml
app/views/static_pages/accessibility_statement.html.haml
app/views/welcome/index.html.haml
config/application.rb
features/static_pages.feature
features/vehicles.feature
features/welcome.feature

Update service banner name to match Vehicle Checker.

Update service banner name

---

.drone2.yml

updated drone sit changes

---

app/controllers/dates_controller.rb
app/views/dates/select_weekly_period.html.haml
app/views/dates/select_weekly_period_input/_errored.html.haml
config/locales/en.yml

https://eaflood.atlassian.net/browse/CAZ-2798

[CAZ-2798] Update error message on `Today or another day` selection page

---

app/controllers/charges_controller.rb
app/controllers/non_dvla_vehicles_controller.rb
app/controllers/vehicles_controller.rb
app/models/confirmation_form.rb
app/models/vrn_form.rb
app/services/session_manipulation/add_vrn.rb
app/services/session_manipulation/base_manipulator.rb
app/services/session_manipulation/set_possible_fraud.rb
app/views/vehicles/incorrect_details.html.haml
app/views/vehicles/not_determined.html.haml
app/views/vehicles/uk_registered_details.html.haml
config/routes.rb
features/step_definitions/vehicle_steps.rb
features/support/mock_helper.rb
features/vehicles.feature
spec/models/vrn_form_spec.rb
spec/requests/vehicles_controller/confirm_uk_registered_details_spec.rb
spec/requests/vehicles_controller/uk_registered_details_spec.rb
spec/services/session_manipulation/add_vrn_spec.rb
spec/services/session_manipulation/set_possible_fraud_spec.rb
spec/support/add_to_session.rb

https://eaflood.atlassian.net/browse/CAZ-2860
https://eaflood.atlassian.net/browse/CAZ-2861
Add flow for possible fraud detection.
Manually, RSpec added and updated.

[CAZ-2860 | CAZ-2861] Detect possible fraud flow

---

pa11y/.pa11yci.conf.js

http://drone-185002984.eu-west-2.elb.amazonaws.com/InformedSolutions/JAQU-CAZ-Payments-UI/55/1/15
Fix accessibility tests

[CAZ-2560] Fix pa11y accessibility tests

---

app/views/charges/review_payment.html.haml
app/views/payments/success.html.haml

[CAZ-2835] rename registration number to number plate

---

app/views/dates/daily_charge.html.haml

[CAZ-2836] Make links full sentences

---

app/services/dates/base.rb
features/charges.feature

https://eaflood.atlassian.net/browse/CAZ-2909

[CAZ-2909] Update D-Day notice

---

.drone2.yml

updated prod deployment steps

---

.drone2.yml

Iac restructure controlled st > sit

---

.drone2.yml

fixes ecs rollout

---

.drone2.yml

fix profile for aws call

---

.drone2.yml

updated fix for sit, preprod and prod deployments

---

package.json

updated package.json with removed changes

---

app/services/chargeable_zones_service.rb

[CAZ-2842] Order cazes alphabetically

---

.drone2.yml

Features/cazb 1784/uat drone changes

---

app/models/vrn_form.rb
app/services/chargeable_zones_service.rb
spec/models/vrn_form_spec.rb

Promote dev to ST v1.3.0

---

app/views/vehicles/vrn_input/_normal.html.haml
config/locales/en.yml
features/vehicles.feature

Jira card: https://eaflood.atlassian.net/browse/CAZ-2950
Updated error messages from the subtasks

[CAZ-2950] Fix error messages

---

app/controllers/dates_controller.rb
app/javascript/packs/datePicker.js
app/services/dates/validate_selected_weekly_date.rb
app/views/dates/select_weekly_date.html.haml
config/locales/en.yml
spec/requests/dates_controller/confirm_date_weekly_spec.rb
spec/services/dates/validate_selected_weekly_date_spec.rb
spec/support/shared_examples/invalid_weekly_selection_date.rb

https://eaflood.atlassian.net/browse/CAZ-3023
Manually, rspec tests added
**D-Day as today:**
**D-Day as three days before today:**
**Manually entered a date before the D-Day (in this case 2020-07-02):**
**Updated the "select date in range" error to include D-Day (default payment window would be 30 June to 12 July):**

[CAZ-3023] Leeds date picker D-Day processing

---

app/services/dates/validate_selected_weekly_date.rb
app/views/dates/select_weekly_date.html.haml
config/locales/en.yml
features/charges.feature
features/taxi.feature
spec/services/dates/validate_selected_weekly_date_spec.rb

[CAZ-2846] date picker content changes

---

app/services/dates/base.rb

https://eaflood.atlassian.net/browse/CAZB-2209
Screenshot from 8 July (D-Day as 2 July):

[CAZB-2209] Display "Came into operation" copy on D-Day + 6

---

app/views/payments/failure.html.haml

https://eaflood.atlassian.net/browse/CAZB-2172

[CAZB-2172] Contact details on Payment Unsuccessful page

---

app/api_wrapper/payments_api.rb
app/controllers/payments_controller.rb
app/models/payment_status.rb
spec/api_wrappers/payments_api/payment_status_spec.rb
spec/models/payment_status_spec.rb

Jira Card: https://eaflood.atlassian.net/browse/CAZB-2198
Removed caz name attribute from payment status request.
Tried to make a payment.

[CAZB-2198] Update payments journey finalisation request to NOT include cleanAirZoneName attribute

---

app/views/static_pages/accessibility_statement.html.haml

https://eaflood.atlassian.net/browse/CAZB-2056

[CAZB-2056] accessibility statement

---

.drone2.yml

drone2 changes migrate to develop branch

---

.drone2.yml

updated st env url

---

app/views/static_pages/accessibility_statement.html.haml

[CAZB-2056] Update gov pay accessibility link

---

.drone2.yml

[CAZB-2027] correct survey link

---

.drone2.yml
Gemfile.lock
app/views/static_pages/accessibility_statement.html.haml

Update ST v1.3.0

---

.drone2.yml

Updated URLs for SIT, Preprod and UAT environments

---

.drone2.yml
Gemfile.lock
app/controllers/charges_controller.rb
features/charges.feature
features/step_definitions/non_uk_vehicles_steps.rb
features/support/session_helper.rb

Update ST with develop

---

additional_url.yml

https://eaflood.atlassian.net/browse/CAZB-2231
* After verification of payments for Bath clean air zone it appears that it required only update of `additional_url.yml` file and update of `public_transport_options_url` in the database.
Manually.
Bath confirmation page:
Updated `public_transport_options_url` in the DEV database:

[CAZB-2231] Bath confirmation page

---

pa11y/.pa11yci.conf.js

[NT] Fix for pa11y test suite

---

.drone2.yml

Cutover SIT domain for Release v1.2.0

Cutover SIT domain for Release v1.2.0

---

.drone2.yml
app/controllers/vehicles_controller.rb
package.json
yarn.lock

https://eaflood.atlassian.net/browse/CAZB-2231

[CAZB-2231] Clear VRN and country when paying for another vehicle

---

app/controllers/charges_controller.rb
app/services/dates/review_weekly_selection.rb
app/views/charges/review_payment.html.haml
features/step_definitions/charges_steps.rb
features/step_definitions/taxi_steps.rb
features/taxi.feature
spec/requests/charges_controller/review_payment_spec.rb
spec/requests/dates_controller/confirm_date_weekly_spec.rb
spec/services/dates/review_weekly_selection_spec.rb

https://eaflood.atlassian.net/browse/CAZB-2225
Manually, rspec and cucumber added
First week selected but no other dates are available:
First week selected and other dates are available:
Second week selected:

[CAZB-2225] Leeds taxi - second week payment review

---

app/views/static_pages/privacy_notice.html.haml

Jira card: https://eaflood.atlassian.net/browse/CAZB-2283
Updated the text in Privacy Notice.

[CAZB-2283] Remove DD info from Privacy Notice

---

app/controllers/charges_controller.rb
app/controllers/dates_controller.rb
app/helpers/application_helper.rb
app/helpers/dates_helper.rb
app/services/dates/assign_back_button_date.rb
app/services/dates/weekly.rb
app/services/session_manipulation/calculate_total_charge.rb
app/views/dates/select_period.html.haml
app/views/dates/select_second_weekly_date.html.haml
app/views/dates/select_weekly_date.html.haml
app/views/dates/select_weekly_date/_content.html.haml
app/views/dates/select_weekly_date/_input_normal.html.haml
app/views/dates/select_weekly_period.html.haml
features/step_definitions/taxi_steps.rb
features/taxi.feature
spec/requests/dates_controller/daily_charges_spec.rb
spec/requests/dates_controller/select_period_spec.rb
spec/requests/dates_controller/select_weekly_date_spec.rb
spec/requests/dates_controller/select_weekly_period_spec.rb
spec/requests/dates_controller/weekly_charges_spec.rb
spec/services/dates/assign_back_button_date_spec.rb
spec/support/add_to_session.rb

https://eaflood.atlassian.net/browse/CAZB-2658
Manually, cucumber and rspec added

[CAZB-2658] Leeds taxi - back button implementation

---

additional_url.yml
app/models/compliance_details.rb
app/views/dates/daily_charge.html.haml
app/views/dates/weekly_charge.html.haml
features/step_definitions/charges_steps.rb
spec/requests/dates_controller/daily_charges_spec.rb
spec/requests/dates_controller/weekly_charges_spec.rb

Update text for IOD and Leeds exemption links

[CAZB-2689, CAZB-2608, CAZB-2594] Update text for IOD and Leeds exemption links

---

.drone.yml
.drone2.yml

https://eaflood.atlassian.net/browse/CAZB-2036
Updated env variable.

[CAZB-2036] Survey Link Update - Qualtrics (Production)

---

app/controllers/dates_controller.rb
app/models/payment.rb
app/views/charges/review_payment.html.haml
spec/models/payment_spec.rb

Jira Card: https://eaflood.atlassian.net/browse/CAZB-2839
I've found a bug that when paying for two weeks for the taxi in Leeds 
It used hardcoded values correct for one week payment only. When user selected two weeks then price total was 2 pence wrong.
Update the methods to calculate the prices based on payment total. 
Additionally fixed Back button issue when used for selected two weeks. 
Tried to make a payment for one and two weeks for Leeds taxit
For 2 weeks: 
For 1 week:

[CAZB-2839] Fix Leeds taxi 2 weekly payments in payment services gov.uk pages displayed the charge as 99.98

---

.drone2.yml

fixed build

---

app/views/payments/failure.html.haml
app/views/vehicles/country_input/_normal.html.haml
app/views/vehicles/details.html.haml
app/views/vehicles/enter_details.html.haml
app/views/vehicles/uk_registered_details.html.haml
app/views/vehicles/unrecognised.html.haml

https://eaflood.atlassian.net/browse/CAZB-2595
https://eaflood.atlassian.net/browse/CAZB-2597

[CAZB-2595] [CAZB-2597] IOD Content

---

app/views/non_dvla_vehicles/index.html.haml

[CAZB-2595] update h1 class for non dvla vehicles

---

.drone2.yml
app/controllers/dates_controller.rb

Release v1.3.1

---

.drone2.yml
Gemfile.lock
additional_url.yml
app/controllers/dates_controller.rb
app/models/compliance_details.rb
app/models/payment.rb
app/views/charges/review_payment.html.haml
app/views/non_dvla_vehicles/index.html.haml
app/views/payments/failure.html.haml
app/views/vehicles/country_input/_normal.html.haml
app/views/vehicles/details.html.haml
app/views/vehicles/enter_details.html.haml
app/views/vehicles/uk_registered_details.html.haml
app/views/vehicles/unrecognised.html.haml
spec/models/compliance_details_spec.rb
spec/models/payment_spec.rb
spec/requests/dates_controller/daily_charges_spec.rb
spec/requests/dates_controller/weekly_charges_spec.rb
spec/requests/payments_controller/success_spec.rb

Update st (Selected commits)

---

app/views/vehicles/country_input/_normal.html.haml

[CAZB-2597] IOD country question

---

app/views/non_dvla_vehicles/index.html.haml

https://eaflood.atlassian.net/browse/CAZB-2870

[CAZB-2870] Text change on non uk page

---

app/views/vehicles/incorrect_details.html.haml
app/views/vehicles/unrecognised.html.haml

https://eaflood.atlassian.net/browse/CAZB-2830
https://eaflood.atlassian.net/browse/CAZB-2868

[CAZB-2830, CAZB-2868] Text change

---

app/controllers/dates_controller.rb
app/controllers/welcome_controller.rb

https://eaflood.atlassian.net/browse/CAZB-2579?focusedCommentId=240678
Dashboard page was cached on Firefox, which caused session details not to be cleared properly

[CAZB-2579] Fix session not clearing after payment on Firefox

---

app/controllers/payments_controller.rb
spec/requests/payments_controller/success_spec.rb

Update RC with selected commit

---

app/controllers/application_controller.rb
app/controllers/payments_controller.rb
spec/requests/payments_controller/index_spec.rb

Update RC 1.4.0 with selected commits

---

Gemfile
Gemfile.lock

Bump rails

---

app/views/vehicles/country_input/_normal.html.haml

https://eaflood.atlassian.net/browse/CAZB-3253

[CAZB-3253] Fix Enter Details page style to match VCCS

---

app/services/chargeable_zones_service.rb
config/environments/development.rb

Remove unused local dns setting

---

app/views/dates/daily_charge.html.haml
app/views/dates/weekly_charge.html.haml

We need to update text for the exception informations.
Jira card: https://eaflood.atlassian.net/browse/CAZB-3484
N/A
Tried to make a payment.

[CAZB-3484] Change exemption wording on tariff page

---

app/views/vehicles/details.html.haml

https://eaflood.atlassian.net/browse/CAZB-3359

[CAZB-3359] Confirm vehicle details page content changes

---

Gemfile
Gemfile.lock
app/controllers/charges_controller.rb
app/controllers/dates_controller.rb
app/services/dates/weekly.rb
app/services/session_manipulation/calculate_total_charge.rb
features/step_definitions/taxi_steps.rb
spec/requests/dates_controller/confirm_select_period_spec.rb
spec/requests/dates_controller/confirm_select_weekly_period_spec.rb
spec/requests/dates_controller/daily_charges_spec.rb
spec/requests/dates_controller/select_weekly_date_spec.rb
spec/requests/dates_controller/select_weekly_period_spec.rb
spec/requests/dates_controller/weekly_charges_spec.rb
spec/spec_helper.rb
spec/support/add_to_session.rb

`fakeredis` needed to pass test locally without started redis-server.

Add test and fakeredis gem

---

.drone2.yml

fixed payments issue

---

.drone2.yml
app/views/payments/failure.html.haml

Jira card: Payment unsuccessful - contact details update
Update contact details.

[CAZB-3764] Payment unsuccessful - contact details update

---

additional_url.yml

Jira Card: https://eaflood.atlassian.net/browse/CAZB-2974
Updated urls

[CAZB-2974] Fix incorrect link to support for Birmingham

---

.drone2.yml
additional_url.yml
app/views/payments/failure.html.haml

Update RC with develop

---

app/views/static_pages/accessibility_statement.html.haml

https://eaflood.atlassian.net/browse/CAZB-3903

[CAZB-3903] Amend content to Accessibility Statement page

---

app/controllers/charges_controller.rb
app/models/compliance_details.rb
app/views/charges/discount_available.html.haml
config/routes.rb
spec/models/compliance_details_spec.rb
spec/requests/charges_controller/discount_available_spec.rb
spec/requests/charges_controller/submit_local_authority_spec.rb

Jira Card: https://eaflood.atlassian.net/browse/CAZB-3869
Added new step for Bath CAZ when vehicle has "phgvDiscountAvailable" flag set.

[CAZB-3869] PHGV discount page

---

config/environments/production.rb

http://drone-1587293244.eu-west-2.elb.amazonaws.com/InformedSolutions/JAQU-CAZ-Payments-UI/685/1/8

[CAZB-2868] Fix deploy - Vehicle not found - change to refund wording

---

app/views/vehicles/unrecognised.html.haml

https://eaflood.atlassian.net/browse/CAZB-2868

[CAZB-2868] Vehicle not found - change to refund wording

---

app/views/non_dvla_vehicles/index.html.haml
app/views/vehicles/incorrect_details.html.haml

https://eaflood.atlassian.net/browse/CAZB-2830
https://eaflood.atlassian.net/browse/CAZB-2870
Revert of revert xD

[CAZB-2830, 2870] Update content

---

README.md
app/api_wrapper/base_api.rb
app/views/non_dvla_vehicles/index.html.haml
app/views/vehicles/incorrect_details.html.haml
app/views/vehicles/unrecognised.html.haml

Update RC with draft

---

pa11y/.pa11yci.conf.js

[CAZB-3986] Accessibility tests fix

---

.drone2.yml

 [CAZB-4063] Migrate pipeline to Terraform v0.12.23 

---

.drone2.yml

Promote release v1.7.1 to pre-production

Promote release v1.7.1 to pre-production

---

package.json
yarn.lock

Fixed https://dev-fleet.paycleanairzonecharge.co.uk/what_would_you_like_to_do

Revert bump expose loader lib

---

app/views/static_pages/privacy_notice.html.haml

[CAZB-4019] Update content on privacy notice page

---

app/views/payments/success.html.haml

* Link to JIRA Card: https://eaflood.atlassian.net/browse/CAZB-4113

[CAZB-4113] Payment complete - link update

---

app/views/payments/success.html.haml

Update draft with develop

---

app/views/charges/discount_available.html.haml

[CAZB-3869] Discount Available wording fix

---

app/views/static_pages/privacy_notice.html.haml
features/static_pages.feature

[CAZB-4145] Privacy Notice update

---

.drone2.yml

[CAZB-4008] Update drone with new Payments URL in prod

[CAZB-4008] Update drone with new Payments URL in prod

---

app/views/static_pages/privacy_notice.html.haml
features/static_pages.feature

Jira Card: https://eaflood.atlassian.net/browse/CAZB-4387

[CAZB-4387] Combine and update Privacy Notice

---

app/views/static_pages/accessibility_statement.html.haml

Jira Card: https://eaflood.atlassian.net/browse/CAZB-4389

[CAZB-4389] Update Accessibility Statement

---

app/controllers/application_controller.rb
app/controllers/charges_controller.rb
app/controllers/dates_controller.rb
app/controllers/non_dvla_vehicles_controller.rb
app/controllers/vehicles_controller.rb
app/controllers/welcome_controller.rb
config/environments/production.rb

[CAZB-4443] Fix firefox headers

---

app/models/compliance_details.rb
app/models/unrecognised_compliance_details.rb
app/views/dates/daily_charge.html.haml
app/views/dates/weekly_charge.html.haml
app/views/payments/success.html.haml
spec/fixtures/files/vehicle_compliance_birmingham_response.json
spec/fixtures/files/vehicle_compliance_discount_taxi_response.json
spec/fixtures/files/vehicle_compliance_many_charges_response.json
spec/fixtures/files/vehicle_compliance_one_charge_response.json
spec/fixtures/files/vehicle_compliance_with_zero_charge_response.json
spec/models/compliance_details_spec.rb
spec/models/unrecognised_compliance_details_spec.rb
spec/requests/dates_controller/daily_charges_spec.rb
spec/requests/dates_controller/weekly_charges_spec.rb
spec/requests/payments_controller/success_spec.rb

* Link to JIRA Card: https://eaflood.atlassian.net/browse/CAZB-4078
* Removed `.additional_urls` file and removed unused code.
N/A

[CAZB-4078] Remove additional urls integration

---

app/controllers/application_controller.rb
app/controllers/charges_controller.rb
app/controllers/non_dvla_vehicles_controller.rb
app/services/chargeable_zones_service.rb
app/services/dates/weekly.rb
spec/spec_helper.rb

Sonar warning - `Define a constant instead of duplicating this literal "local-authority" 3 times.`
Also added code documentation check for private methods (same as for all projects)

Fix code smell and code documentation

---

app/views/static_pages/privacy_notice.html.haml

Updated privacy policy to add CCC section

---

.drone2.yml
yarn.lock

Bump yarn libs

---

.drone2.yml
yarn.lock

Bump yarn libs (#621)

---

app/models/caz.rb
app/views/static_pages/privacy_notice.html.haml
spec/models/caz_spec.rb

https://eaflood.atlassian.net/browse/CAZB-4713

[CAZB-4713] Use operator name on privacy policy page

---

.drone2.yml

http://drone-1587293244.eu-west-2.elb.amazonaws.com/InformedSolutions/JAQU-CAZ-Customer-Service-UI/1304/1/6

Exclude advisory from yarn audit until it is fixed

---

app/controllers/application_controller.rb
app/exceptions/invalid_host_exception.rb
app/services/security/host_header_validator.rb
config/application.rb
spec/services/security/host_header_validator_spec.rb

Jira Card: https://eaflood.atlassian.net/browse/CAZB-4653

[CAZB-4653] Fix Host header vulnerability

---

.rubocop.yml
app/controllers/application_controller.rb
app/controllers/dates_controller.rb
app/controllers/vehicles_controller.rb
app/models/compliance_details.rb
app/services/chargeable_zones_service.rb
app/services/session_manipulation/base_manipulator.rb
app/services/session_manipulation/set_vehicle_details.rb
app/views/dates/daily_charge.html.haml
features/step_definitions/vehicle_steps.rb
features/support/mock_helper.rb
features/vehicles.feature
spec/fixtures/files/undetermined_vehicle_with_type_details_response.json
spec/models/compliance_details_spec.rb
spec/requests/vehicles_controller/details_spec.rb
spec/requests/vehicles_controller/uk_registered_details_spec.rb
spec/services/chargeable_zones_service_spec.rb
spec/services/session_manipulation/set_vehicle_details_spec.rb

Jira Card: https://eaflood.atlassian.net/browse/CAZB-4203
Updated the flow to use the vehicle type from the DVLA if present (for undetermined compliance vehicle)
Used TST010 Vehicle to pay for.
For `TST010`
For `TST010` Undetermined without type:

[CAZB-4203] Clarify Process flow requirement for partial record returns

---

app/views/vehicles/not_determined.html.haml

[CAZB-4204] Change text about contact

[CAZB-4204] Change text about contact

---

.rubocop.yml
app/controllers/application_controller.rb
app/controllers/dates_controller.rb
app/controllers/vehicles_controller.rb
app/exceptions/invalid_host_exception.rb
app/models/compliance_details.rb
app/services/chargeable_zones_service.rb
app/services/security/host_header_validator.rb
app/services/session_manipulation/base_manipulator.rb
app/services/session_manipulation/set_vehicle_details.rb
app/views/dates/daily_charge.html.haml
config/application.rb
features/step_definitions/vehicle_steps.rb
features/support/mock_helper.rb
features/vehicles.feature
spec/fixtures/files/undetermined_vehicle_with_type_details_response.json
spec/models/compliance_details_spec.rb
spec/requests/vehicles_controller/details_spec.rb
spec/requests/vehicles_controller/uk_registered_details_spec.rb
spec/services/chargeable_zones_service_spec.rb
spec/services/security/host_header_validator_spec.rb
spec/services/session_manipulation/set_vehicle_details_spec.rb

Promote r-c/v2.4.0 to ST

---

app/views/vehicles/unrecognised.html.haml

Minor typography correction on vehicle details not found page.

[CAZB-4877] Minor typography correction

---

app/views/vehicles/unrecognised.html.haml

Reverts InformedSolutions/JAQU-CAZ-Payments-UI#650 due to inclusion of strong tag on ending parenthesis

Revert "[CAZB-4877] Minor typography correction"

---

app/views/vehicles/unrecognised.html.haml

Minor typography correction to fix spacing in Payments UI shown below:

[CAZB-4877] Typography correction

---

app/controllers/application_controller.rb
app/services/security/host_header_validator.rb
spec/services/security/host_header_validator_spec.rb

[CAZB-4854] Allow multiple hosts

---

app/views/static_pages/privacy_notice.html.haml

https://eaflood.atlassian.net/browse/CAZB-4834

[CAZB-4834] Privacy notice amendments

---

app/controllers/vehicles_controller.rb
features/step_definitions/vehicle_steps.rb
features/vehicles.feature
spec/requests/vehicles_controller/enter_details_spec.rb

Jira Card: https://eaflood.atlassian.net/browse/CAZB-4755

[CAZB-4755] Clear VRN data upon entering /enter_details page

---

package.json
yarn.lock

[CAZSM-237] revert postcss upgrade

---

.drone2.yml

http://drone-1587293244.eu-west-2.elb.amazonaws.com/InformedSolutions/JAQU-CAZ-Payments-UI/1114/1/12

Fix accessibility tests

---

.drone2.yml
ci-cd-resources/pa11y/.pa11yci.conf.js
ci-cd-resources/pa11y/Dockerfile

[CAZB-4960] Fix accessibility tests

---

package.json
yarn.lock

[CAZSM-242] bump dns-packet and css-what

---

.drone2.yml
.iyarc
package.json
yarn.lock

Added security tests dev and st CI.
Reverted unnecessary changes in package.json.([link](https://github.com/InformedSolutions/JAQU-CAZ-Payments-UI/commit/530bc278f9944ba736f96e503745bb0cb064c533), [link2](https://eaflood.atlassian.net/browse/CAZSM-242))
Updated excluded list for yarn audit.

Add security tests and update `.iayrc` file

---

app/views/layouts/_cookie_control.html.erb
app/views/layouts/_gtm_script.html.erb
app/views/layouts/application.html.haml
config/initializers/content_security_policy.rb

[CAZB-4897] Update "unsafe-inline" CSP policy to use nonces

---

app/controllers/vehicles_controller.rb
features/step_definitions/vehicle_steps.rb
features/support/mock_helper.rb
features/vehicles.feature
spec/fixtures/files/vehicle_details_taxi_without_typye_response.json

Jira Card: https://eaflood.atlassian.net/browse/CAZB-4995
Tested with taxi MH31HGV

[CAZB-4995] Fix Incomplete registered Taxi does not navigate to CAZ selection page

---

.rubocop.yml
Gemfile
Gemfile.lock
README.md
app/api_wrapper/base_api.rb
app/javascript/packs/application.js
config/application.rb
sonar-project.properties
spec/requests/application_controller/build_id_spec.rb
spec/requests/application_controller/health_spec.rb
spec/services/session_manipulation/clear_session_details_spec.rb
yarn.lock

https://eaflood.atlassian.net/browse/CAZB-4194
Add ruby lib to fix loading gem in production mode.
https://www.rubydoc.info/gems/addressable/Addressable/URI

[CAZB-4194] Update Base API to handle well non-ascii URIs (#770)

---

.drone2.yml
.rubocop.yml
Gemfile
Gemfile.lock
README.md
app/api_wrapper/base_api.rb
app/controllers/vehicles_controller.rb
app/javascript/packs/application.js
config/application.rb
features/step_definitions/vehicle_steps.rb
features/support/mock_helper.rb
features/vehicles.feature
sonar-project.properties
spec/fixtures/files/vehicle_details_taxi_without_typye_response.json
spec/requests/application_controller/build_id_spec.rb
spec/requests/application_controller/health_spec.rb
spec/services/session_manipulation/clear_session_details_spec.rb
yarn.lock

Update RC 2.5.0

---

app/models/vrn_form.rb
features/step_definitions/vehicle_steps.rb

[CAZB-3877] Permit all language characters

[CAZB-3877] Permit all language characters for non-UK vehicles

---

app/assets/stylesheets/no-javascript.css
app/views/common/_js_back_link.html.haml

https://eaflood.atlassian.net/browse/CAZB-4788

[CAZB-4788] Fix js back button

---

config/initializers/content_security_policy.rb

[CAZB-4788] Fix console warning

---

config/initializers/content_security_policy.rb

Revert [CAZB-4788] Fix console warning (#687)

---

Gemfile.lock
app/views/dates/_details.html.haml
app/views/dates/daily_charge.html.haml
app/views/dates/weekly_charge.html.haml
app/views/non_dvla_vehicles/index.html.haml
app/views/payments/failure.html.haml
app/views/vehicles/unrecognised.html.haml
app/views/welcome/index.html.haml

Content updates:
* https://eaflood.atlassian.net/browse/CAZB-5068
* https://eaflood.atlassian.net/browse/CAZB-5067
* https://eaflood.atlassian.net/browse/CAZB-5062
* https://eaflood.atlassian.net/browse/CAZB-5061
* https://eaflood.atlassian.net/browse/CAZB-5060

[CAZB-5068] Updated content associated with paying period

---

app/views/dates/_details.html.haml
app/views/dates/daily_charge.html.haml
app/views/dates/weekly_charge.html.haml
app/views/non_dvla_vehicles/index.html.haml
app/views/payments/failure.html.haml
app/views/vehicles/unrecognised.html.haml
app/views/welcome/index.html.haml

Content updates after change in cards:
https://eaflood.atlassian.net/browse/CAZB-5068
https://eaflood.atlassian.net/browse/CAZB-5067
https://eaflood.atlassian.net/browse/CAZB-5062
https://eaflood.atlassian.net/browse/CAZB-5061
https://eaflood.atlassian.net/browse/CAZB-5060

[CAZB-5068] Updated content associated with paying period - time

---

app/views/dates/_details.html.haml
app/views/dates/daily_charge.html.haml
app/views/dates/weekly_charge.html.haml
app/views/non_dvla_vehicles/index.html.haml
app/views/payments/failure.html.haml
app/views/vehicles/unrecognised.html.haml
app/views/welcome/index.html.haml

Promote patch fixes to ST

---

.drone2.yml

[CAZB-4710] Lower domain switchover

[CAZB-4710] Lower domain switchover

---

.drone2.yml

Draft release candidate/v2.4.2 corrected

Draft release candidate/v2.4.2 corrected

---

app/controllers/application_controller.rb
spec/requests/static_pages_controller_spec.rb

Jira Card: https://eaflood.atlassian.net/browse/CAZB-5104

[CAZB-5104] Update service to flag Invalid Host Headers with 403 error

---

app/views/vehicles/not_determined.html.haml
app/views/vehicles/unrecognised.html.haml

[CAZB-5049] Content update

---

app/views/vehicles/unrecognised.html.haml

Remove duplicate id attribute on unrecognised page

---

Gemfile.lock
app/views/vehicles/unrecognised.html.haml

[CAZB-5092] Update vehicle details not found page

---

Gemfile.lock
app/views/vehicles/incorrect_details.html.haml

[CAZB-5094] Incorrect vehicle details - update content

---

app/controllers/charges_controller.rb
app/controllers/vehicles_controller.rb
app/views/vehicles/incomplete.html.haml
app/views/vehicles/not_determined.html.haml
app/views/vehicles/unrecognised.html.haml
config/routes.rb
features/step_definitions/path_expectations.rb
features/vehicles.feature
spec/requests/charges_controller/local_authority_spec.rb
spec/requests/vehicles_controller/confirm_details_spec.rb
spec/requests/vehicles_controller/incomplete_spec.rb

https://eaflood.atlassian.net/browse/CAZB-5082

[CAZB-5082] Add vehicle details incomplete page

---

app/controllers/charges_controller.rb
app/services/caz_data_provider.rb
app/views/charges/_one_zone.html.haml
app/views/charges/_undetermined_vehicle_notice.haml
app/views/charges/local_authority.html.haml
app/views/dates/daily_charge.html.haml
features/step_definitions/charges_steps.rb
features/step_definitions/non_uk_vehicles_steps.rb
features/step_definitions/payments_steps.rb
features/step_definitions/taxi_steps.rb
features/step_definitions/vehicle_steps.rb
spec/requests/charges_controller/local_authority_spec.rb
spec/services/caz_data_provider_spec.rb

* Link to JIRA Card: https://eaflood.atlassian.net/browse/CAZB-5084

[CAZB-5084] Incomplete undetermined flow update

---

app/controllers/charges_controller.rb
app/controllers/vehicles_controller.rb
app/services/caz_data_provider.rb
app/views/charges/_one_zone.html.haml
app/views/charges/_undetermined_vehicle_notice.haml
app/views/charges/local_authority.html.haml
app/views/dates/daily_charge.html.haml
app/views/vehicles/incomplete.html.haml
app/views/vehicles/not_determined.html.haml
app/views/vehicles/unrecognised.html.haml
config/routes.rb
features/step_definitions/charges_steps.rb
features/step_definitions/non_uk_vehicles_steps.rb
features/step_definitions/path_expectations.rb
features/step_definitions/payments_steps.rb
features/step_definitions/taxi_steps.rb
features/step_definitions/vehicle_steps.rb
features/vehicles.feature
spec/requests/charges_controller/local_authority_spec.rb
spec/requests/vehicles_controller/confirm_details_spec.rb
spec/requests/vehicles_controller/incomplete_spec.rb
spec/services/caz_data_provider_spec.rb

Draft release candidate/v2.5.1

---

app/controllers/dates_controller.rb
app/views/dates/daily_charge_for_incomplete.html.haml
features/taxi.feature
spec/requests/dates_controller/daily_charges_spec.rb

* https://eaflood.atlassian.net/browse/CAZB-5083

[CAZB-5083] Update CAZ tariff page for incomplete vehicle details
